### ISSUE TITLE
Duplicate serial outdoor unit

### ISSUE THREAD

**Issue by arkadicolson** [embee8/homebridge-panasonic-ac-platform#14]
Hi

For the outdoor temp unit the default serial number is used. This makes my setup having it double used because another plugin which has it not configurable also makes it double used now ;-)
Maybe making it a config option?

Just small improvement, not urgent at all...

Thx!

**Comment by embee8** [comment]
Good shout! May I ask which serial number you see in the Home app? I assume it's "only" the serial number in the Home app, and not the UUID that Homebridge uses to tell accessories apart?

**Comment by arkadicolson** [comment]
The serial number is "Default-SerialNumber"

![IMG_4584](https://user-images.githubusercontent.com/6794568/150295687-a0bb18e4-cc05-44b5-a9e0-405e36cb3fa1.PNG)

The conflicting plugin is ShellyDoorbell

Thanks for looking into this!

**Comment by embee8** [comment]
Thank you, that's very helpful.

Does this double allocation lead to any kind of malfunction on the Home app at all?

**Comment by arkadicolson** [comment]
Nope, that's why I said not urgent at all ;-) The "Controller" app reports this which could lead to incomplete/corrupt backups and restores in case of emergency.

![image](https://user-images.githubusercontent.com/6794568/150347765-2168841e-8901-48bd-ba10-f3eee2186abf.png)

**Comment by embee8** [comment]
Have a look at ba5672e. I tried to keep it simple and added a dummy serial number. "HB-PACP" stands for "Homebridge Panasonic AC Platform" and serves as a scope in this context.
