### ISSUE TITLE
Message of unavailable temperature appears every minute when AC is switched off

### ISSUE THREAD

**Issue by efipso** [embee8/homebridge-panasonic-ac-platform#17]
Related with closed issue #9 (wich I cannot re-open), sorry if a new issue is not necessary

Finally I've learned how to correctly debug a homebridge instance...

There you have the log: https://gist.github.com/efipso/ac6e9c9ed9c07fb8ccbc626c9ee71945
I've just removed all lines not refering this plugin and deleted IDs from my device/connection

Hope this log can help you

**Comment by embee8** [comment]
Thank you! Closing this issue and re-opened the original one.
