### ISSUE TITLE
Can't find on HOOBS?

### ISSUE THREAD

**Issue by miguelsasso** [embee8/homebridge-panasonic-ac-platform#18]
Hi

Do you have any idea why I can't find this plugin on hoobs? 

(I would rather not have to switch over to homebridge-config-ui).

Thanks

**Comment by embee8** [comment]
I am not familiar with HOOBS, but after briefly checking their website, it seems that they filter the plugins and don't make all of them available on their own (?) plugin store. This is best addressed directly with the maker of the software/box.
