### ISSUE TITLE
Support for +8-15 Heat mode

### ISSUE THREAD

**Issue by onkelfarmor** [embee8/homebridge-panasonic-ac-platform#19]
My AC has a +8-15 Heat mode for use in winter. This mode is not accessible in the plugin. When set to this mode in the app and 11 degrees, the plugin shows Heat and 16 degrees. 

![8AE800AE-0D61-4C5E-B204-C8B333929C6D](https://user-images.githubusercontent.com/7473641/151652150-44949081-98cf-4439-b7da-aa1791906f28.jpeg)
![5D3A7BB7-095D-495E-9FB9-40943791C4C7](https://user-images.githubusercontent.com/7473641/151652153-a06ce440-1226-46ed-bf50-54b52edebfc7.jpeg)

**Comment by embee8** [comment]
Hi! Are you able to provide a device status payload (which you will see when enabling debug mode)?

Also, which AC model do you operate?

**Comment by onkelfarmor** [comment]
Model: CS-NZ25VKE

Device status payload (think this is what you want - when set on +8-15 Heat with 8 degrees:
  dryTempMin: -1,
  modeAvlList: { autoMode: 1, fanMode: 1 },
  airSwingLR: true,
  nanoe: false,
  autoMode: true,
  autoSwingUD: false,
  ecoNavi: false,
  heatTempMax: -1,
  temperatureUnit: 0,
  iAutoX: false,
  coolTempMin: -1,
  autoTempMin: -1,
  quietMode: true,
  powerfulMode: true,
  timestamp: 1643557664000,
  fanMode: true,
  coolMode: true,
  summerHouse: 2,
  coolTempMax: -1,
  permission: 3,
  dryMode: true,
  nanoeStandAlone: false,
  heatMode: true,
  fanSpeedMode: -1,
  dryTempMax: -1,
  autoTempMax: -1,
  fanDirectionMode: -1,
  ecoFunction: 0,
  heatTempMin: -1,
  pairedFlg: false,
  parameters: {
    ecoFunctionData: 0,
    airSwingLR: 2,
    nanoe: 0,
    lastSettingMode: 0,
    ecoNavi: 0,
    ecoMode: 0,
    operationMode: 3,
    fanAutoMode: 3,
    temperatureSet: 8,
    fanSpeed: 5,
    iAuto: 0,
    airQuality: 0,
    insideTemperature: 21,
    outTemperature: 5,
    operate: 1,
    airDirection: 1,
    actualNanoe: 0,
    airSwingUD: 0
  }
}

**Comment by embee8** [comment]
Thanks! Out of curiosity, what is the purpose of this mode? How does it differ to the standard heating mode?

It looks like both heating modes (the normal one and the 8-15) report the same value for `operationMode`, which is 3.

The difficulty here is that HomeKit and Homebridge don't offer a secondary heating mode, and therefore we would have to update the characteristic's minimum and maximum values on the fly. Do you see any fields in this API response which would distinguish those two heating modes?

**Comment by onkelfarmor** [comment]
The purpose of the mode is for use in the winter period to use in eg. a garage or the link and avoid it being to cold.

As I see it, it differs with fever settings when on this mode - eg. I can't change the fan speed in the app when on this mode. However, I have also integrated the Heater in Home Assistant, and there I can change every setting even in this mode. So maybe it is just on the app level, that this mode exists.

I also think the only way to fix it is to make an extra setting, where we can change minimum values.

**Comment by onkelfarmor** [comment]
Just checked - when I in Home Assistant change temp. fra eg. 20 to 12, in the app the mode changes from Heat to +8-15 Heat mode. So it is maybe just an app thing and we just need to have the setting.

**Comment by embee8** [comment]
Interesting! So it sounds like if we add an option to lower the minimum heating temperature from 16 to 8 degrees, the Panasonic app would take care of the rest. Would you agree based on your observations so far?

**Comment by onkelfarmor** [comment]
> Interesting! So it sounds like if we add an option to lower the minimum heating temperature from 16 to 8 degrees, the Panasonic app would take care of the rest. Would you agree based on your observations so far?

Yes

**Comment by embee8** [comment]
Have a look at #20 and let me know what you think. I did some local testing and as far as the HomeKit UI is concerned, it all looks good.

A limitation is that we can't remove other settings that are not available when the 8-15 mode is enabled, for example the fan speed. But given that this change doesn't affect standard operation and only gives flexibility to those who need it, there shouldn't be any harm in shipping this.

**Comment by onkelfarmor** [comment]
Please help me what command to write in terminal in homebridge to install this branch.

**Comment by embee8** [comment]
Apologies for the delay, @onkelfarmor. I had the PR lying around for some time but only got to refine and merge it today. This repository doesn't have a beta channel yet, so you can simply find the new feature in the latest release (v1.3.0). Let me know whether this fixes your issue.
