### ISSUE TITLE
Siri not Recognizing turn off mode

### ISSUE THREAD

**Issue by Mani1082** [embee8/homebridge-panasonic-ac-platform#22]
Hey 👋🏻 
I’ve encountered a problem since the latest iOS update. I can normally turn on my units but when I want to turn it off it says the same message as when it turns it on and won’t turn the units off. 
is it linked to the plug-in ?
Thanks

**Comment by embee8** [comment]
Hi! I can't tell but a way to find out is through pressing the buttons in the Home app instead of asking Siri. If the buttons work as intended, then it's a Siri-related issue which is beyond the scope of this plugin as it's abstracted away from us.
