### ISSUE TITLE
Outdoor Temperature and Temperature State not available 

### ISSUE THREAD

**Issue by 1homebridge** [embee8/homebridge-panasonic-ac-platform#23]
I am not able to get the temperature reading
Log says
Outdoor Temperature is not available 
Temperature State is not available 

How can I resolve this
Thanks

**Comment by embee8** [comment]
Can you share your JSON config (remove username and password)?

I suspect you configured the plugin to expose an outdoor unit (which reports the outdoor temperature), but you might not have this capability in your system.

**Comment by 1homebridge** [comment]
Hi
Pls find my config below
     “name": "Homebridge Panasonic AC Platform",
     "email": "xxx@xxx.com",
     "password": "xxx",
     "exposeOutdoorUnit": true,
     "debugMode": false,
     "platform": "Panasonic AC Platform"

I have multiple in ceiling units and external units. In the Comfort Cloud App, I do get an external temperature reading. I also got a temperature reading with a previous plug-in I used. So I’m hoping I can find a solution to this. 

Many Thanks

**Comment by embee8** [comment]
Setting `exposeOutdoorUnit` to false will get rid of the error. Your external unit doesn't report the outside temperature in the same way as others or doesn't report it at all. The way to find out is to enable debug mode and look at the API responses for your units.

**Comment by 1homebridge** [comment]
Hi
In the accessories listed in the HomeBridge accessories, I get an External Unit accessory that shows the outdoor temperature, but this accessory only shows up in the HomeBridge UI. There is no accessory coming up in the Home App; not that such an accessory is required, but it would be helpful if the temperature reading shown in the HomeBridge Accessories section was incorporated in the reading of the units as currently it shows a 0*C. 
Thanks

**Comment by embee8** [comment]
Is the temperature reading in the Homebridge UI correct, i.e. does it match with the perceived outdoor temperature?

My hunch is that the unit exists in Homebridge because you enabled the creation in the plugin configuration. But if that unit doesn't physically exist in your home (could be that your system reports outdoor temperature in a different way), then the Home App could ignore or discard it.

Screenshots and log entries would help to get to the bottom of it.

**Comment by embee8** [comment]
Thanks for the thorough investigation and clear explanation! I will close this issue and continue the discussion in #31 which covers the same topic. I will come back to your findings above to produce a solution for your kind of setup.
