### ISSUE TITLE
Status Bar and Cooling Icon

### ISSUE THREAD

**Issue by 1homebridge** [embee8/homebridge-panasonic-ac-platform#26]
I was using the previous plug-in which used to provide a cooling or heating status in the status bar of each room/level but I am not getting this function with this plug-in. I would also get a change in the colour icon of each unit based on activity from Green to Blue when Cooling and to Orange when Heating. Is this option available with this plug-in. 
Thanks

**Comment by embee8** [comment]
Is this due different plugin functionality or due to a change in HomeKit, i.e. how Apple chooses to display it? Do you have a reference implementation of a plugin that achieves these UI distinctions?

**Comment by 1homebridge** [comment]
Hi
Thank you for getting back to me. Prior to using this plug-in, I was using the Panasonic Air Conditioner plug-in by Cody1515 which has now been archived. He mentioned that your plug-in is based on the same coding, the difference being that yours uses the platform rather than individual accessories/units (trying to explain this as best as I can but my knowledge is pretty basic) His plug-in also did not initially update the status bar nor did it control the icon colour based on setting, Green for Standby, Blue for Cooling and Orange for Heating. But one of the last updates included these functions which were quite useful. So for example, when using the cooling option, the Green Circle would turn Blue and the Status Bar on the top of the Room/Level would change from Idle to Cooling and note the temperature much like the Heatmiser accessories would show the Room was Heating. I hope this clarifies the “issue”.  As I am very dependent on this plug-in, I would be willing to donate but there is not such option on your plug-in. 
Many Thanks

**Comment by 1homebridge** [comment]
![51A744C6-4E99-41A8-8D41-CCC0F9242DE7](https://user-images.githubusercontent.com/90335348/166614878-a5bcfe18-796b-44d1-ace8-8f48405304a3.jpeg)
![82631082-4BC1-4F9B-AEB1-1754A795D599](https://user-images.githubusercontent.com/90335348/166614879-887af2e5-b8fa-41be-806b-b30eb7a98b8c.jpeg)

**Comment by 1homebridge** [comment]
I’m attaching screenshots I found of the features I was trying to explain. 
This is the Status Bar up top that shows that the AC is on Cooling and the Temperature of the Room

![CC464FF9-99DF-4C9B-8E66-D7BAD97B646D](https://user-images.githubusercontent.com/90335348/166615030-b1e5d549-def2-45ae-9edc-71ba1db3aafb.jpeg)

And this is a side by side of my Underfloor Heating on Standby (Green) and the AC on Cooling (Blue) and again showing the Temperature within the circle. 

![C118FBA1-0A95-48D4-BED4-FD5E7A1D0B7B](https://user-images.githubusercontent.com/90335348/166615131-bb3aaeaa-29c8-4344-bd22-4e4d163a3bb5.jpeg)

I hope this helps

Thanks again

**Comment by embee8** [comment]
The results of my debugging session suggest that we might be dealing with a Homebridge or HomeKit bug.

1) The status icon in the Home app is controlled by the [CurrentHeaterCoolerState characteristic](https://developers.homebridge.io/#/characteristic/CurrentHeaterCoolerState) of the accessory.

2) On [this line](https://github.com/embee8/homebridge-panasonic-ac-platform/blob/a8bdd2ea702707f6533e78451779b8f56957f736/src/accessories/indoor-unit.ts#L208), we set the current state to IDLE when the AC is in cooling mode and the current temperature is less than the set temperature. However, in my test the Home app displays the status of the AC as inactive.

3) In my debugging session, I also tried setting the current state to INACTIVE instead of IDLE and I got the same result on the UI.

4) As an additional test, I set the current state to HEATING. The Home app UI reflected this correctly (as Heating), which leaves me thinking that Homebridge or HomeKit don't distinguish between the IDLE and INACTIVE modes.

**Comment by embee8** [comment]
@1homebridge, upon further exploration I can confirm that I actually see the "Cooling" indicator and the blue arrow in my Home app.

![image](https://user-images.githubusercontent.com/12213984/169924420-9f714bb5-c038-46d7-b270-d62ee6193d0f.png)

In your previous comments, you uploaded images of how you want it to look like, but can you upload a screenshot of how it actually looks like for you right now?

My previous comment alleged a bug with regards to how IDLE and INACTIVE lead to the same UI representation. It does not, however, confirm your original thesis of the indicators not being available at all. Could you help me clarify the problem statement?

**Comment by embee8** [comment]
The overlap between the IDLE and INACTIVE statuses is addressed in [this issue](https://github.com/homebridge/homebridge/issues/3145) in the Homebridge repository.

**Comment by JurgenLB** [comment]
can you set Debug to "true" in your config. Restart and post the output from your log.
Maybe we can resolve the issue then.

My config looks like this;
    `{
            "name": "Homebridge Panasonic AC Platform",
            "email": "xxxxxxxxxxxxxxxxxxx@xxx.xxx",
            "password": "xxxxxxxxxxxxxxxxxx",
            "exposeOutdoorUnit": true,
            "debugMode": true,
            "platform": "Panasonic AC Platform"
        },`

**Comment by embee8** [comment]
@1homebridge, is this the same type of issue as in #23 and #31?

**Comment by 1homebridge** [comment]
Hi, thanks for getting back to me.
Yes, though with the new UI in iOS16 the Status Bar no longer indicates between Idle-Cooling-Heating states so the issue is just to obtain an indoor temperature reading from the outdoor unit as described in #23 and #31 to stop getting a 0.0* indicator. This would then allow the units to show the Blue colour indicating that they are in Cooling mode as requested in the other threads. 
Thanks

**Comment by embee8** [comment]
Okay, thanks for confirming and the additional context. Will deal with it through the other open issues.
