### ISSUE TITLE
Can't change temperature

### ISSUE THREAD

**Issue by marwi234** [embee8/homebridge-panasonic-ac-platform#30]
If i ask for changing the temperature in Homekit, the phone can't find any devices that support temperature control. 
No Problem with changing to automatic-mode, cooling-mode, heating-mode. Everithing else is really good. Thanks

(Edit: removed file download link)

**Comment by embee8** [comment]
Hi @marwi234! Could you create a [Gist](https://gist.github.com/) with your log entry or embed it as code block in your post in case it's a shorter one? This is a more secure way than having people download raw files.

**Comment by marwi234** [comment]
https://gist.github.com/marwi234/df468bba82cc3c854254721869e30c6f

**Comment by xdejiko** [comment]
seem homekit problem and updated to ios 15.5 would fix it
