### ISSUE TITLE
Only get On/Off functionality

### ISSUE THREAD

**Issue by mstendah** [embee8/homebridge-panasonic-ac-platform#32]
Hi,

wonder what is wrong here as I can only turn my Panasonic ACs on or off, but not adjust any temperature etc.
Further more, they don't appear in Apple Homekit at all, only in the Homebridge accessories menu.

**Comment by mstendah** [comment]
I stand corrected. This was something temporary and now works.

**Comment by embee8** [comment]
That’s great. Thanks for reporting back.
