### ISSUE TITLE
"characteristic was supplied illegal value" errors

### ISSUE THREAD

**Issue by johnsonwalker** [embee8/homebridge-panasonic-ac-platform#41]
Started getting these errors today out of the blue:

```
[16/09/2022, 2:43:24 pm] [homebridge-panasonic-ac-platform] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://homebridge.io/w/JtMGR for more info.
[16/09/2022, 2:43:24 pm] [homebridge-panasonic-ac-platform] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://homebridge.io/w/JtMGR for more info.
```

Tried manually setting the minimum temperature to 0 via the plugin settings but that didn't work.

**Comment by JurgenLB** [comment]
I think you have a "extra heater" in your device,

from config.schema.json;
`      "minHeatingTemperature": {
        "title": "Minimum heating temperature (override)",
        "description": "The default heating temperature range is 16-30°C. Some Panasonic ACs have an additional heating mode for the range of 8-15°C. If you own such a model, you can use this setting to adjust the minimum value. Leave it empty or undefined to use the default value.",
        "type": "integer",
        "placeholder": "16"`

**Comment by embee8** [comment]
@johnsonwalker, did you restart Homebridge after adjusting the configuration? That would be required for the changes to take effect.

**Comment by LukeEcosystem** [comment]
hi, I'm new in this community. I want to ask for a secondary account with Panasonic comfort cloud. when I'm trying to create the second account is not letting me, because I'm putting the same Device id. can someone help me with what to do, please?

**Comment by JurgenLB** [comment]
For the first time to connect I have used 2 on remote.
For sub accounts I have used 3 on remote.
So my workflow for sub-account is;
- open app
- new ID with different E-mail
- 5 sec WiFi button (on remote)
- 3 “set” (on remote)
- enter password 
- Put in message for main-account “text”

After this the main-account must accept the request

**Comment by LukeEcosystem** [comment]
Thanks Jurgen I will give it a try

**Comment by embee8** [comment]
> hi, I'm new in this community. I want to ask for a secondary account with Panasonic comfort cloud. when I'm trying to create the second account is not letting me, because I'm putting the same Device id. can someone help me with what to do, please? and another thing on the temps is saying "[Homebridge Panasonic AC Platform] Temperature state is not available

Hi! Please create a new issue for this rather than inserting a different problem statement into an existing topic.
