### ISSUE TITLE
Fetching device status: 504 Gateway Timeout

### ISSUE THREAD

**Issue by JurgenLB** [embee8/homebridge-panasonic-ac-platform#44]
with the latest version I get;
  status: 504,
  statusText: 'Gateway Time-out',

  status: 502,
  statusText: 'Bad Gateway',

I have 3 devices.
So are we pulling to fast from te server or do you think there is something else wrong ?

`[23/10/2022, 11:43:14] [Homebridge Panasonic AC Platform] Comfort Cloud - getDeviceStatus() for GUID 'CS-Z35VKEW+4962414538': Error
[23/10/2022, 11:43:14] [Homebridge Panasonic AC Platform] {
  status: 502,
  statusText: 'Bad Gateway',
  headers: {
    date: 'Sun, 23 Oct 2022 09:43:13 GMT',
    'content-type': 'text/html; charset=utf-8',
    'content-length': '150',
    connection: 'close',
    server: 'nginx'
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json; charset=UTF-8',
      'Content-Type': 'application/json',
      'User-Agent': 'G-RAC',
      'X-APP-TYPE': '0',
      'X-APP-VERSION': '1.16.0',
      'X-User-Authorization': ''
    },
    method: 'get',
    url: 'https://accsmart.panasonic.com/deviceStatus/no',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'accsmart.panasonic.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'accsmart.panasonic.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 78677,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /deviceStatus/now/' +
      'Accept: application/json; charset=UTF-8\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: G-RAC\r\n' +
      'X-APP-TYPE: 0\r\n' +
      'X-APP-VERSION: 1.16.0\r\n' +
      'X-User-Authorization: ' +
      'Host: accsmart.panasonic.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/deviceStatus/now/,
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 502,
      statusMessage: 'Bad Gateway',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://accsmart.panasonic.com/deviceStatus/now/',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'accsmart.panasonic.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://accsmart.panasonic.com/deviceStatus/',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'x-app-type': [Array],
      'x-app-version': [Array],
      'x-user-authorization': [Array],
      host: [Array]
    },
    [Symbol(kUniqueHeaders)]: null
  },
  data: '<html>\r\n' +
    '<head><title>502 Bad Gateway</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>502 Bad Gateway</h1></center>\r\n' +
    '<hr><center>nginx</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}
[23/10/2022, 11:43:14] [Homebridge Panasonic AC Platform] An error occurred while refreshing the device status. Turn on debug mode for more information.`

`[23/10/2022, 11:51:43] [Homebridge Panasonic AC Platform] Accessory: Refresh status for device 'Living'
[23/10/2022, 11:51:43] [Homebridge Panasonic AC Platform] Comfort Cloud: getDeviceStatus() for device GUID 'CS-Z35VKEW+4962414538'
[23/10/2022, 11:51:43] [Homebridge Panasonic AC Platform] Accessory: Refresh status for device 'Speelkamer'
[23/10/2022, 11:51:43] [Homebridge Panasonic AC Platform] Comfort Cloud: getDeviceStatus() for device GUID 'CS-Z25VKEW+4962312857'
[23/10/2022, 11:51:44] [Homebridge Panasonic AC Platform] Comfort Cloud - getDeviceStatus() for GUID 'CS-Z35VKEW+4962414538': Error
[23/10/2022, 11:51:44] [Homebridge Panasonic AC Platform] {
  status: 504,
  statusText: 'Gateway Time-out',
  headers: {
    server: 'awselb/2.0',
    date: 'Sun, 23 Oct 2022 09:51:44 GMT',
    'content-type': 'text/html',
    'content-length': '132',
    connection: 'close'
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json; charset=UTF-8',
      'Content-Type': 'application/json',
      'User-Agent': 'G-RAC',
      'X-APP-TYPE': '0',
      'X-APP-VERSION': '1.16.0',
      'X-User-Authorization': ''
    },
    method: 'get',
    url: 'https://accsmart.panasonic.com/',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'accsmart.panasonic.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'accsmart.panasonic.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 92269,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /deviceStatus/now/ HTTP/1.1\r\n' +
      'Accept: application/json; charset=UTF-8\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: G-RAC\r\n' +
      'X-APP-TYPE: 0\r\n' +
      'X-APP-VERSION: 1.16.0\r\n' +
      'X-User-Authorization: +
      'Host: accsmart.panasonic.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 3,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 504,
      statusMessage: 'Gateway Time-out',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: '',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'accsmart.panasonic.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: '',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'x-app-type': [Array],
      'x-app-version': [Array],
      'x-user-authorization': [Array],
      host: [Array]
    },
    [Symbol(kUniqueHeaders)]: null
  },
  data: '<html>\r\n' +
    '<head><title>504 Gateway Time-out</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}
[23/10/2022, 11:51:44] [Homebridge Panasonic AC Platform] An error occurred while refreshing the device status. Turn on debug mode for more information.
[23/10/2022, 11:51:44] [Homebridge Panasonic AC Platform] Comfort Cloud - getDeviceStatus() for : Success
[23/10/2022, 11:51:44] [Homebridge Panasonic AC Platform] {
  fanMode: false,
  modeAvlList: { autoMode: 1, fanMode: 1 },
  coolMode: true,
  airSwingLR: false,
  summerHouse: 0,
  nanoe: false,
  permission: 2,
  dryMode: true,
  nanoeList: { visualizationShow: 0 },
  autoMode: true,
  nanoeStandAlone: false,
  heatMode: true,
  autoSwingUD: false,
  ecoNavi: false,
  temperatureUnit: 0,
  iAutoX: false,
  quietMode: true,
  ecoFunction: 0,
  powerfulMode: true,
  timestamp: ,
  pairedFlg: false,
  parameters: {
    ecoFunctionData: 0,
    airSwingLR: 1,
    nanoe: 1,
    lastSettingMode: 0,
    ecoNavi: 0,
    ecoMode: 0,
    operationMode: 3,
    fanAutoMode: 1,
    errorStatus: -255,
    temperatureSet: 22,
    fanSpeed: 3,
    iAuto: 0,
    airQuality: 0,
    insideTemperature: 19,
    outTemperature: 16,
    nanoeDevice: -255,
    operate: 0,
    airDirection: 0,
    actualNanoe: 1,
    airSwingUD: 0
  }
}`

**Comment by embee8** [comment]
I found a similar entry in my logs, but it's not consistent. 5xx are server errors. It might just be a transient infrastructure error or an updated logic on their end. We'll have to keep monitoring and examining why the server responds with an error in some cases.

**Comment by JurgenLB** [comment]
Ok I will close it for now but we keep monitoring it.
Thanks for the recommendation I dit not notice that.

**Comment by embee8** [comment]
I continue to see these error messages. I will try to space the API calls out - maybe that resolves it.

**Comment by embee8** [comment]
@JurgenLB, just wanted to check in how the situation looks like on your end at the moment. All stable or do you still have the 504 entries in your log?

**Comment by JurgenLB** [comment]
I just checked my logs and there are no 5xx entries anymore. So all stable for the moment.

But I found this message in the app;
![image](https://user-images.githubusercontent.com/77586573/201735918-042bb81e-75d1-4c91-806d-01a9c0210413.png)

![image](https://user-images.githubusercontent.com/77586573/201736043-2027316b-9126-45eb-9a7e-f80d4378fd8e.png)

I hope this will not affect your platform

Thanks for the good work

**Comment by embee8** [comment]
This seems to primarily have targeted the official mobile apps, but thanks a lot for the heads-up.
