### ISSUE TITLE
Unable to do automation with indoor temperature

### ISSUE THREAD

**Issue by blackcodefr** [embee8/homebridge-panasonic-ac-platform#46]
When trying to make an automation. It only shows "turns on" of "turns off" as state change automation on each unit instead of exposing a current indoor value for each unit.

It seems the indoor temperature of each unit is not exposed properly as the current indoor temperature does show in the Home app on the dashboard.

**Comment by embee8** [comment]
Do you have other devices in your home leveraging Homebridge's [Heater Cooler](https://developers.homebridge.io/#/service/HeaterCooler) where this is possible?

**Comment by blackcodefr** [comment]
This plugin does it : 

https://github.com/smithersDBQ/homebridge-fujitsu

**Comment by blackcodefr** [comment]
Did you find the information you were looking for ?

**Comment by embee8** [comment]
Thanks! I had a look at the code and saw that that plugin uses the [Thermostat](https://developers.homebridge.io/#/service/Thermostat) service, rather than the Heater Cooler that we do.

As a next step, I'll research whether this is a limitation of Homebridge we have to live with, or if (and how) we can adjust the current implementation to allow for the indoor temperature to be used for automation purposes as well.

**Comment by blackcodefr** [comment]
Hi, hoping Christmas went well. As a follow up, i have installed the home bridge plug-in for my Tesla and automation with temperature is also possible.

**Comment by blackcodefr** [comment]
Il using the verified Tesla plug-in for Homebridge.

**Comment by embee8** [comment]
Confirming that the [Tesla plugin](https://github.com/nfarina/homebridge-tesla) also uses the Thermostat service, see [here](https://github.com/nfarina/homebridge-tesla/blob/3f8ef6d237d7b9367408d50c4dd66a2bf60e7551/src/services/ClimateService.ts#L15).

Either way, I noticed just now that somehow the current temperature of the AC units of this plugin is now available for automation purposes. Can you see the same on your end?

**Comment by mkz212** [comment]
I can confirm. I have current temperature, target temperature etc. in automations. 

But I think that using current temperature of AC in automation is bad because AC always show wrong temp. Instead of this, use external temp sensor or even many sensors. I have something like: if one of sensors have smaller temp that i want - turn on heating. If all sensors have bigger temperature than i want - turn off heating.

**Comment by blackcodefr** [comment]
I still can't. Which version of iOS are you using ?

**Comment by mkz212** [comment]
iOS 16.3 but this is not a new feature, it was in previous versions.

**Comment by blackcodefr** [comment]
It doesn't show on 16.2 for me in automation but HomeKit does display current temperature for each AC.

**Comment by mkz212** [comment]
Describe step by step what you are doing and what exactly you want to achieve. 

Do you convert automation to shortcut? Next add If module? Next in If module select Home accessory? Select AC and here what options You have?

![562722F3-A1BF-423F-ABB1-7B22B1BE3025](https://user-images.githubusercontent.com/82271669/214507757-aad5db8c-6f89-4ba0-82b1-700f83f0e847.png)

**Comment by blackcodefr** [comment]
In the home app, Automation tabs tap + then :

1. Select "A sensor signals something":

![image](https://user-images.githubusercontent.com/1132747/214545435-1d5a4586-caa7-4cf8-9377-6f0c6996181b.png)

2. Selecting AC from Tesla or Fujitsu plugin:

![IMG_6642](https://user-images.githubusercontent.com/1132747/214546093-798c92b4-df86-417a-b508-1945754a0406.png)

3. After clicking Next it allows automation for going above or below temperature

![IMG_6645](https://user-images.githubusercontent.com/1132747/214546292-52875c34-ef09-47cc-ae00-cf8581865b89.png)

2'. Selecting AC from this plugin:

![IMG_6645](https://user-images.githubusercontent.com/1132747/214546463-93b8e91e-c842-4494-9a6f-42d49b15af17.png)

3'. After clicking Next it allows automation for the AC being turned on or off instead of selection temperature going above or below a value:

![IMG_6647](https://user-images.githubusercontent.com/1132747/214546707-c2217f11-104c-407f-a5d5-d7f4402056e9.png)

**Comment by mkz212** [comment]
I really don,t understant sense of this? What You want to achieve? 

My suggestions:
1. Convert to shortcut. You can use Eve app to set more than one time based trigger. 
2. If You don't want to convert to shortcut You can do something like: if temp of X device go below temp you set than turn on Y device. You can also choice mode (heat, cool, auto), rotation speed, swing mode, and target temp. 


![97D9E1BC-5A8A-4BE6-A5BE-29EFBCE21919](https://user-images.githubusercontent.com/82271669/214559713-24d3b19f-d279-44fc-b9ff-b8c7d1cc55fc.png)
![DA94A5C2-5595-4FCE-BAFF-EBA2F751C426](https://user-images.githubusercontent.com/82271669/214559717-7281ceb6-af7b-45c1-9ec9-65569df28cb5.png)

**Comment by embee8** [comment]
@blackcodefr, maybe it's worth removing and re-adding the Homebridge instance from your Home app. I was able to verify your bug report last year but when I checked again yesterday, I had the same options available as the ones you described under "3. After clicking Next it allows automation for going above or below temperature" (re Tesla and Fujitsu plugins).

**Comment by mkz212** [comment]
@blackcodefr now I understand what You want. But I have options in this plugin to triger when temp go below or above. So maybe try Remove one accessory from cache (you can find this option in homebridge settings).

**Comment by embee8** [comment]
> But I think that using current temperature of AC in automation is bad because AC always show wrong temp. Instead of this, use external temp sensor or even many sensors.

I'd refrain from calling specific ways of doing things 'bad' or 'good'. Each user has a slightly different setup and looks at things from their own perspective.

In fact, the norm in [control systems engineering](https://en.wikipedia.org/wiki/Control_engineering) is to "*measure the output performance of the process being controlled*". If we use our AC to control the inside temperature, we need to measure the inside temperature as control variable, regardless of what the outside temperature is. Typically, the latter isn't a primary input for automation because the cooling/heating output will depend on the size of the space, insulation of the building, etc.

**Comment by mkz212** [comment]
As I wrote "I think" - which makes it clear that this is just my personal opinion based on my experiences. Some air conditioners (e.g. Gree) have a temperature sensor in the remote control because the manufacturers came to the conclusion that the sensor in the unit does not work as it should.

**Comment by blackcodefr** [comment]
> @blackcodefr, maybe it's worth removing and re-adding the Homebridge instance from your Home app. I was able to verify your bug report last year but when I checked again yesterday, I had the same options available as the ones you described under "3. After clicking Next it allows automation for going above or below temperature" (re Tesla and Fujitsu plugins).

Ok I will try tonight. Thanks guys.

**Comment by mkz212** [comment]
@blackcodefr I hope that You solve this?

**Comment by blackcodefr** [comment]
Unfortunately not. But I think it's because I still had cache. Got sick couldn't check how to remove cache after deleting sub bridge yet.

**Comment by mkz212** [comment]
Do You try this?:
1. Go to Homebridge settings
2. Go to bottom and find option „Remove one accessory from cache”
3. Select Your AC
4. Restart Home app

**Comment by blackcodefr** [comment]
I followed your procedure and it worked. A bug thank you to two for your involvement and help.

**Comment by embee8** [comment]
Perfect - glad it works for you now. Thanks @mkz212 for your support as well.
