### ISSUE TITLE
airDirection?

### ISSUE THREAD

**Issue by osthoren** [embee8/homebridge-panasonic-ac-platform#50]
Hi, 

I love this plugin!

I wonder if it's possible to set the airDirection somehow? 

I use other sensors in my house to trigger on/off behaviour, and no matter if I choose "oscillate" or not in the automation, the airDirection is either in 0% or 100% of the range.

Can I somehow set it like this?
![image](https://user-images.githubusercontent.com/9367281/206720010-1183e859-9766-4937-ac73-0c4b187619ee.png)

Br,
Oscar

edit: I found the properties airSwingLR and airSwingUD, so if I get it running locally I can hard code the values.
edit 2: I removed the swing functionality and always set the values of airSwingLR/UD to the wanted values.

**Comment by Mani1082** [comment]
Hi, could you show me how it looks like in config file ?
Thanks

**Comment by osthoren** [comment]
> Hi, could you show me how it looks like in config file ?
> 
> Thanks

Hi,

My config looks just the same as before. I've downloaded the plugin locally and set the airSwingUD values in the method sending the update to the Panasonic API to always be 2 I think it was.

**Comment by Mani1082** [comment]
> > Hi, could you show me how it looks like in config file ?
> > Thanks
> 
> Hi,
> 
> My config looks just the same as before. I've downloaded the plugin locally and set the airSwingUD values in the method sending the update to the Panasonic API to always be 2 I think it was.

I’m a noob in configuration. How do you access the plugin root to modify those values ? I know that from the raspberry pi’s terminal there’s a way to access it bit I just don’t remember how. 
Thx

**Comment by embee8** [comment]
Hi! Looks like you found a workaround/solution that works for you, hence I'll close the issue.

For anyone not comfortable with setting up such local overrides, I don't recommend going down that path because any changes are overwritten whenever the plugin is updated.
