### ISSUE TITLE
DEBUG mode not working

### ISSUE THREAD

**Issue by ursusHU** [embee8/homebridge-panasonic-ac-platform#51]
I turned on the debug mode option at the advanced options of the plugin settings, however, the log is full with the entry:
`[15/12/2022, 02:18:48] [Homebridge Panasonic AC Platform] An error occurred while refreshing the device status. Turn on debug mode for more information.`
So it is impossible to find out what the actual problem is.

**Comment by embee8** [comment]
Did you restart Homebridge after enabling the debug mode?
