### ISSUE TITLE
Panasonic CONEX Zone Controller support

### ISSUE THREAD

**Issue by Klaays** [embee8/homebridge-panasonic-ac-platform#52]
I am looking to purchase a Panasonic ducted system with zone controls.
I may be able to contribute to this project but wanted to check if zone control would be possible with the integration method or if it may already work with the current release of this project?

**Comment by embee8** [comment]
Hi! Unfortunately I don't know whether it already works with the current version, or whether it could be adapted to support it. There are a number of outstanding items on the roadmap which I will prioritise before being able to look into new ones.
