### ISSUE TITLE
Fan speed to auto

### ISSUE THREAD

**Issue by miguelsasso** [embee8/homebridge-panasonic-ac-platform#55]
Hello

As far as I can see, HomeKit does not support setting fan speed to auto. 

Currently, this plugin turns off the air con when setting fan speed to 0%, which offers no benefit to user. Would it be possible to change plugin behaviour such that fan speed 0% = auto?

**Comment by mkz212** [comment]
Set fan speed to 6 in homekit

**Comment by embee8** [comment]
This will be incorporated as part of #28. Please head over there for any additional comments.

**Comment by miguelsasso** [comment]
> 

I’m not sure what you mean. The fan slider doesn’t appear to show any numbers?
