### ISSUE TITLE
Too many logins error

### ISSUE THREAD

**Issue by hajar97** [embee8/homebridge-panasonic-ac-platform#60]
After installing this homebridge plugin in a few days I got kicked out of the Panasonic Cloud Comfort app. Every time I try to login I get E0011 Internal Server Error, which apparently corresponds to too many logins. Through homebridge logs I see that Homebrdige plugin cannot login to Panasonic Cloud Comfort either. And before when it was successfully logging in it would do that every 2-3 mins, which is what I guess led to getting kicked out of the Panasonic Cloud Comfort. Until I got kicked out, both the app and Homebridge Plugin worked well. 

Any idea how to limit frequency at which this plugin pings and tries to login to Panasonic Cloud Comfort or any other suggestion how to resolve this issue?

**Comment by embee8** [comment]
Hi! The v1.4.1 release that dropped yesterday includes an update to the login behaviour. The latest version only attempts to login 5 times. I recommend installing the latest version and checking if that helps.

I'd let some time pass, and then check if you can log into the Comfort Cloud app again and your Homebridge plugin instance works as well.

Lastly, could you paste the sanitised API response that contains the referenced E0011 error? This might be helpful for further debugging and future development.

**Comment by hajar97** [comment]
Hi,

Yes, after disabling the plugin, waiting for 24 hours I was able to login again through the app. I then tried enabling plugin again and it seems to have logged in as well, with the following strange warnings:

[25/01/2023, 11:39:20] [Homebridge Panasonic AC Platform] Successfully logged in.
[25/01/2023, 11:39:20] [Homebridge Panasonic AC Platform] Configuring outdoor unit.
[25/01/2023, 11:39:20] [Homebridge Panasonic AC Platform] Discovering devices on Comfort Cloud.
[25/01/2023, 11:39:21] [Homebridge Panasonic AC Platform] Adding accessory 'First floor' (CZ-RTC6BLW+7061BEE9B4C3).
[First floor@@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
[First floor@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
[25/01/2023, 11:39:21] [Homebridge Panasonic AC Platform] Adding accessory 'Ground floor' (CZ-RTC6BLW+7061BE8C3D2D).
[Ground floor@@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
[Ground floor@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
[25/01/2023, 11:39:21] [Homebridge Panasonic AC Platform] Adding accessory 'Second floor' (CS-Z50XKEW+4887109302).
[Second floor@@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
[Second floor@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16

Not sure what those mean and why they happen. 

Regarding API response, where can I see them? Do I need to enable debug mode to see those response in the logs?

**Comment by embee8** [comment]
Good to hear, thanks for confirming. I'll close out this issue since it was created around the login error that seems resolved.

Regarding the threshold temperature topic, please open a new issue and add the API payloads which you will see after enabling the debug mode like you said.
