### ISSUE TITLE
'Plugin site not available' error when trying to install plugin

### ISSUE THREAD

**Issue by maevans1969** [embee8/homebridge-panasonic-ac-platform#64]
Hello
I am getting the error 'Plugin site not available' error when trying to install the plugin.

Can you advise how I can install the plugin?

I have confirmed connectivity from my HOOBS box to the internet.

Thanks
Mark

**Comment by embee8** [comment]
Hi! The issue doesn't seem related to the plugin itself. For support for the commercial HOOBS product, see [here](https://support.hoobs.org/).
