### ISSUE TITLE
Swing Mode still doesn't work

### ISSUE THREAD

**Issue by mkz212** [embee8/homebridge-panasonic-ac-platform#68]
After todays update swing mode still doesn't work as it should. When I change Oscilate in Home App it change setting in Panasonic Comfort Cloud app. But when I change setting in Comfort Cloud app it doesn't change in Home app. I have default settings in config.

```
"swingModeDirections": "LEFT-RIGHT-UP-DOWN",
"swingModeDefaultPositionLeftRight": "CENTER",
"swingModeDefaultPositionUpDown": "CENTER",
```

when I remove second part from:

```
deviceStatus.fanAutoMode === ComfortCloudFanAutoMode.AirSwingAuto
          && this.platform.platformConfig.swingModeDirections
          === SwingModeDirection.LeftRightAndUpDown

```

so it be: 

`deviceStatus.fanAutoMode === ComfortCloudFanAutoMode.AirSwingAuto`

it works.

So problem is with:

```
this.platform.platformConfig.swingModeDirections
          === SwingModeDirection.LeftRightAndUpDown
```

**Comment by mkz212** [comment]
it is line 303 in indoor-unit.ts

**Comment by embee8** [comment]
Issue closed, what's the conclusion?

**Comment by mkz212** [comment]
Sorry. Everything worked. Home app just have delay.
