### ISSUE TITLE
Can't connect issue

### ISSUE THREAD

**Issue by patrickyuen1** [embee8/homebridge-panasonic-ac-platform#78]
Please help with the issue below, 
tried these method but still not working: 1. create new panasonic account. 2. reset everything

02/10/2023, 16:15:26Panasonic Ac Platform BridgeHomebridge Panasonic AC PlatformERRORLogin failed. Skipping device discovery.
02/10/2023, 16:15:26Panasonic Ac Platform BridgeHomebridge Panasonic AC PlatformERRORThe Comfort Cloud server might be experiencing issues at the moment. The plugin will try to log in again in 360 seconds. If the issue persists, make sure you configured the correct email and password and run the latest version of the plugin. Restart Bridge when you change your config.

**Comment by mkz212** [comment]
1. Open Panasonic app and accept terms (if dialog appears). 
2. Change app version in homebridge plugin to 1.19.0

**Comment by patrickyuen1** [comment]
thanks, I have already changed app version in homebridge plugin to 1.19.0

**Comment by mkz212** [comment]
If this doesn't help see #75 .  You need change one file.

**Comment by embee8** [comment]
This should now be fixed (once you updated to the latest app version).
